version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 4000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 7788
      POSTGRES_DB: homelibrary
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - my_network
    restart: always

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 7788
      POSTGRES_DB: homelibrary
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  pgdata: