version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: ${POSTGRES_USERNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - my_network
    restart: always
    volumes:
      - app_data:/app/data
  
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_logs:/var/log/postgresql
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  app_data:
  pg_data:
  pg_logs: